#!/usr/bin/env bash

DB_NAME="${MYSQL_DATABASE:-postbox}"

mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS ${DB_NAME};
    CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
    GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '$MYSQL_USER'@'%';
    FLUSH PRIVILEGES;
EOSQL
