name: Docker Compose Test

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '8.0'
            laravel: 9
          - php: '8.1'
            laravel: 10
          - php: '8.2'
            laravel: 11
          - php: '8.3'
            laravel: 11
          - php: '8.4'
            laravel: 11

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'desk'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Create a new laravel application
        run: composer create-project laravel/laravel app "${{ matrix.laravel }}.x" --remove-vcs --no-interaction --prefer-dist

      - name: Link Desk Repository
        run: |
          composer config minimum-stability dev
          composer config repositories.desk path ../desk
          composer require laravel/desk:* --dev -W
        working-directory: app

      - name: Install Desk into App
        run: |
          php artisan desk:install --php=${{ matrix.php }} --no-interaction
          php artisan desk:publish --no-interaction
        working-directory: app

      - name: Remove Desk
        run: composer remove laravel/desk --dev --no-interaction -W
        working-directory: app

      - name: Start Desk Container
        run: ../desk/bin/desk up -d --wait
        working-directory: app

      - name: Run Migrations
        run: ../desk/bin/desk artisan migrate --no-interaction
        working-directory: app

      - name: Run Tests in Desk Container
        run: ../desk/bin/desk test
        working-directory: app

      - name: Stop Desk Container
        run: ../desk/bin/desk down
        working-directory: app
